### ISSUE TITLE
need to calculate IMD and persist

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#5] opened 2022-02-15 09:43 UTC
```
    index_of_multiple_deprivation=CharField( # TODO need to calculate IMD and persist
```

https://github.com/rcpch/rcpch-audit-engine/blob/4cafd1c7bdc158daf59f164c65a5e6317529099e/rcpch-audit-engine/epilepsy12/models.py#L188

**Comment by pacharanero** [comment] 2022-02-15 18:01
This is a duplicate of #4

**Closed** 2022-02-18 12:00 UTC
Labels: feature request
