### ISSUE TITLE
Organisational Audit

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#798] opened 2024-02-20 15:08 UTC
Adding features as issues for later prioritisation

Add the organisational audit form, to be completed by Lead Clinicians. This needs to be completed once per Trust. 
The form opens on 1 November each year, and remains open until the following 31st January. So the 2023 Organisational Audit was open 01/11/2023 - 31/01/2024. 

The dataset is here - https://www.rcpch.ac.uk/sites/default/files/2023-12/epilepsy12_round_4_organisational_audit_dataset_v1_20231128.pdf

**Comment by eatyourpeas** [comment] 2024-05-18 10:51
This is a duplicate of #876

**Closed as completed by eatyourpeas** 2024-05-18 10:51 UTC
Labels: duplicate, feature request, priority: high
