### ISSUE TITLE
NHS Number Error

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#516] opened 2023-07-06 16:04 UTC
![Image](https://user-images.githubusercontent.com/126471383/251506258-0322495b-db4f-4c14-9abb-f3c293ec6b3b.PNG)

I couldn't add a new patient, as the platform flagged the NHS number as the wrong number of digits. 
I tried 076 102 2163 and that also didn't work. 883 501 0039 did work. These numbers came from a random generator - http://danielbayley.uk/nhs-number/

I assume it rejected the first two attempts as the NHS number began with 0.

**Comment by eatyourpeas** [comment] 2023-07-06 16:07
Yes that is correct. At least the error handling is working! @pacharanero has since created a new package for NHS numbers with a number of colleagues from across the health tech community and our testing branch has that working. So I will leave this issue here for the moment, but once the testing branch has merged (probably tomorrow) into development, we can close this. Thank you for spotting!

**Comment by anchit-chandran** [comment] 2023-07-07 09:19
Duplicate of / will be fixed on completion of #515

**Comment by eatyourpeas** [comment] 2023-07-20 19:02
this is now fixed

**Closed as completed by eatyourpeas** 2023-07-20 19:02 UTC
Labels: duplicate
