### ISSUE TITLE
DESSCRIBE  question flow

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#88] opened 2022-08-27 14:56 UTC
so this is a biggie really, sorry...

By definition those in the audit will have epilepsy.  However a child may have a number of different types of episode with at least one of those episodes being epileptic.  They may have several epileptic types of episodes.  Along with epileptic seizures they may have non-epileptic and uncertain episodes.

Therefore each child may have several (ie one to many) seizure types each with 
-D a description
-E confirmation whether that seizure type is 'epileptic or non-epileptic or uncertain' 
- a date of onset for that seizure type
- Whether that date of onset is approximate, exact or not know
- and for those seizure types confirmed as epileptic then for that seizure type their should be fields allowing that seizure type to be defined as focal onset, generalised onset, unknown onset or unclassified with the selectable terms.

i think it might be easier to have the following questions in the epilepsy context section rather than within the DESSCRIBE flow:

Has the child at any point in time experienced prolonged focal seizures > 5 min duration (or successive continuing > 5min)? 
Has the child at any point in time experienced prolonged generalised convulsive seizures > 5 min duration (or successive continuing > 5min)?
With regards to the seizures leading to the diagnosis of epilepsy, were any convulsive? 

S is ok

C  There can be several causes or a cause that mean a number of the 6 headings can be selected. Somehow 1 or more of these 6 should be selectable

**Comment by eatyourpeas** [comment] 2022-08-27 16:50
So this has big implications for our current data structure.
We should therefore change our design so that we deprecate the desscribe class, since that is not a discrete entity. A child's epilepsy can have only one syndromic diagnosis, one cause and one set of relevant impairments either behavioural or educational (ie one to one for SCRIBE), but is made up of multiple episodes each with their own description and seizure type (ie one episode to many DES).
Can you confirm?:
1. A child's epilepsy can only have one cause (ie it cannot be both autoimmune and genetic)
2. One seizure episode can only have one seizure type (irrespective of whether epileptic or nonepileptic)?

That being the case we should instead:

- [ ] deprecate DESSCRIBE as a class
- [ ] introduce an Episode class which has a many to one relationship with Registration
- [ ] Episode class captures date of episode (as well as confidence in the date), episode description with keywords, epilepsy status (is the episode epileptic/nonepileptic or uncertain), and for those episodes that are epileptic or nonepileptic, their type of onset.

If each episode can in turn have multiple seizure type (again, either epileptic or nonepileptic) then we shall have to abstract that out into its own class, probably having an EpilepsySeizureType class and a NonepilepsySeizureType class, each which has a many relation to one Episode.

**Comment by coldunk** [comment] 2022-08-28 08:50
1 episode type = 1 description = 1 statement as to whether epileptic, non-epileptic or uncertain, and if that stated as epileptic = 1 seizure type

1 child at 1 point in time has 1 epilepsy syndrome type.  There are a few who progress from 1 to another but this is not in a 12 month period and only have 1 at a time. Ie have epileptic spasms and then later Lennox gastaut. Or have CAE and later JAE. 

1 epilepsy can have several causes for example cerebral palsy and tuberous sclerosis

1 cause can have several categories for example tuberous sclerosis is genetic and structural!

Shall I draw diagram as that might help us be sure?

**Comment by eatyourpeas** [comment] 2022-08-28 12:33
Ok this is very helpful, but far more complicated than I have built. 
I think we are in danger of trying to build an epilepsy classification system (which reading around is the Holy Grail) when we should be building an audit. If you are sure we need this level of detail to report on national standards of care then we can of course build it. Do you currently report on this level of detail? How does knowing the different types and different causes of seizure (both epileptic and nonepileptic) influence the standard of service they receive? Is it surely not enough to know if it is epilepsy or not epilepsy, maybe the cause if known, that they are being seen in a timely way, having the right tests and seeing the right people and having the right care plans? If we are asking colleagues to log every seizure type, every cause (genetic/metabolic/structural etc) they will spend longer entering data as they have to dig through each child's epilepsy journey in more detail. I have made this process quicker by getting rid of as many dropdowns as possible in favour of toggles and radio buttons, but once options go above about 3 or 4, dropdowns are unavoidable. Finding the sweet spot between getting the most information for the least clinician effort is the only priority driving my questions - do please see them as such and are in no way critical.

Until now we have had one DESSCRIBE model per registration (which would capture only one seizure type, one cause, one description etc). Not real life, but I had understood that ultimately DESSCRIBE summarised a child's epilepsy into a single paradigm. In fact now we are talking about having one MultiaxialDescription class per registration, with each record referencing multiple Episode class instances (each of which has a description, seizure definition and seizure type), multiple Cause class instances (each of which has a category and potentially a subcategory) and multiple Comorbidity class instances (each of which has a behavioural or educational comorbidity).

I will start converting what we have in place along these lines. It would probably be helpful for us to review this item regularly as we go to make sure I don't make any more assumptions in future and find myself backpedalling. If you are happy with this I will list out a set of items to sign off before closing this issue.

**Comment by coldunk** [comment] 2022-08-28 13:12
Shall we chat as keen to keep as simple as suits our aspirations.  What I have described matches what we do at moment in current live platform.  

Some elements are needed
Seizure type influences criteria for tertiary referral but this is whether there is myoclonus or not. 
Syndrome type influences MRI indication
Other elements inform the diagnostic demographics of the cohort but don’t feed the performance indicators. 

You are right that this therefore potential captures a classification beyond everything the audit requires. 

We could take out capturing multiple epilepsy syndromes and only include epileptic seizure types and this would serve the audit fine. We could go further. 

Somewhere in the epilepsy digital landscape there will need to be something that nails this multiaxial classification that we can API with.  We could park this classification wizard element if wish and just do the bare bones of DESSCRIBE that are purely the audit basic building blocks?!  

Colin

On 28 Aug 2022, at 13:33, Simon Chapman ***@***.***> wrote:

﻿
Ok this is very helpful, but far more complicated than I have built.
I think we are in danger of trying to build an epilepsy classification system (which reading around is the Holy Grail) when we should be building an audit. If you are sure we need this level of detail to report on national standards of care then we can of course build it. Do you currently report on this level of detail? How does knowing the different types and different causes of seizure (both epileptic and nonepileptic) influence the standard of service they receive? Is it surely not enough to know if it is epilepsy or not epilepsy, maybe the cause if known, that they are being seen in a timely way, having the right tests and seeing the right people and having the right care plans? If we are asking colleagues to log every seizure type, every cause (genetic/metabolic/structural etc) they will spend longer entering data as they have to dig through each child's epilepsy journey in more detail. I have made this process quicker by getting rid of as many dropdowns as possible in favour of toggles and radio buttons, but once options go above about 3 or 4, dropdowns are unavoidable. Finding the sweet spot between getting the most information for the least clinician effort is the only priority driving my questions - do please see them as such and are in no way critical.

Until now we have had one DESSCRIBE model per registration (which would capture only one seizure type, one cause, one description etc). Not real life, but I had understood that ultimately DESSCRIBE summarised a child's epilepsy into a single paradigm. In fact now we are talking about having one MultiaxialDescription class per registration, with each record referencing multiple Episode class instances (each of which has a description, seizure definition and seizure type), multiple Cause class instances (each of which has a category and potentially a subcategory) and multiple Comorbidity class instances (each of which has a behavioural or educational comorbidity).

I will start converting what we have in place along these lines. It would probably be helpful for us to review this item regularly as we go to make sure I don't make any more assumptions in future and find myself backpedalling. If you are happy with this I will list out a set of items to sign off before closing this issue.

**Comment by eatyourpeas** [comment] 2022-08-28 21:51
I think we should get as close to this as you are happy with and see how long it takes to complete for the average user. This is a first attempt for the DESS elements:

This is the list view:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1058647/187095878-af425de3-ee5c-4c3f-b948-708e9f995b97.png">

Which points to the detail view:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/1058647/187095819-efff943d-46f8-48fd-a721-e4336b1af4bb.png">
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/1058647/187095838-b83ee8c9-9a4f-4485-aa2a-caf7b0034418.png">

**Closed** 2022-09-01 16:05 UTC
Labels: bug, for-mvp
