### ISSUE TITLE
List of children who are missing audit fields

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#543] opened 2023-08-04 15:30 UTC
E.g. a list with clickable links to the children who have not met tertiary input. E12 team to provide requested KPIs to appear

![Image](https://user-images.githubusercontent.com/68898006/258463878-ca34c34e-7726-45c1-a981-73c07595f6be.png)

**Comment by eatyourpeas** [comment] 2024-05-18 11:00
duplicate of #797

**Closed as completed by eatyourpeas** 2024-05-18 11:00 UTC
Labels: duplicate, feature request
