### ISSUE TITLE
Allow users to view multiple Trusts

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#802] opened 2024-02-21 12:54 UTC
We have a number of users who will need to have access to organisations across multiple Trusts on the platform. Can we implement this?
For example, clinicians working across multiple Trusts but have only one email address. or ICB leads.

**Comment by eatyourpeas** [comment] 2024-02-21 13:27
This is possible in one of two ways - @pacharanero says it is possible to create multiple email addresses using the same one using the + character eg lead.clinician+organisation_name@email.com. Or we could add multiple organisations to the person's profile - possibly tidier, but need more time as it would need testing because filtering across the app currently only takes account of a single organisation, not multiple. Doable though.

I would be grateful if it could be added to the list of requested features so that project board can prioritise what they would like and we can think about implementing.

**Comment by eatyourpeas** [comment] 2024-05-18 10:48
this is a duplicate of #879

**Closed as completed by eatyourpeas** 2024-05-18 10:48 UTC
Labels: duplicate, feature request
