### ISSUE TITLE
Can't recreate a deleted patient

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#725] opened 2023-12-20 15:50 UTC
A user had to delete a patient because they entered their first paediatric assessment date incorrectly, but now they have been unable to recreate the patient 

"So I have deleted her off the list but when I try and put him back on, it will not accept his NHS number saying NHS number previously used, but when I search for the patient with that nhs number its says the child doesn’t exisit.
An IT problem I think.
Let me know  what im supposed to do."

I also tried to create the patient myself, about an hour after her email, and the same error appeared.

**Comment by eatyourpeas** [comment] 2023-12-20 22:14
I have not been able to reproduce this in the staging site - everything seems to be working as expected there. Are you sure the NHS number used is correct?
Is it possible to send me the NHS number privately and I will investigate in the admin or in the shell?

**Comment by AmaniKrayemRCPCH** [comment] 2024-01-02 13:04
Sorry I don't have the NHS number anymore. It definitely wasn't working on the live site at the time.

**Comment by eatyourpeas** [comment] 2024-01-02 19:58
Forgive me @AmaniKrayemRCPCH I wasn't saying you were wrong, just that it is hard for me to troubleshoot without more information. Is there any way we could find from the user more information? Very happy to chat on a call.

**Comment by AmaniKrayemRCPCH** [comment] 2024-01-04 14:51
I was able to get the patient's NHS number. I haven't tried to re-add them to the platform but I can see that they're not currently there. I'm happy to hop on a call to give you the number and try adding them to the platform.

**Comment by AmaniKrayemRCPCH** [comment] 2024-01-09 13:21
Relevant to this issue, another patient has 'disappeared' from the platform but is still in the dataset and i can see them in the admin panel. It appears they aren't assigned to an organisation. 

User said they completed the record and then the record was suddenly deleted.

**Comment by eatyourpeas** [comment] 2024-01-13 13:12
I am going to close this issue as resolved. If this happens again please post a new issue.

**Closed as completed by eatyourpeas** 2024-01-13 13:12 UTC
Labels: bug, priority: highest
