### ISSUE TITLE
Tab 2 first paediatric assessment

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#138] opened 2022-10-16 13:23 UTC
* [x] 'Date of first paediatric assessment' entered at add new patient stage and should not be editable here.  It should be visible but not editable on tab 1.

* [x] Involving general paediatrics is a redundant field as described here (all children by definition will be under general paediatrics because had first paediatric assessment).  Does it really mean referral to 'Paediatrician with Expertise in Epilepsies' in which case it should be somewhere but  better captured in tab 5.

Regarding consistency of questions around the information gathered at first paediatric assessment:

- [x] rename 'Full paediatric clinical examination' as 'General examination'

- [x] rename 'Full neurological examination' as 'Neurological examination'

- [x] rename 'Learning, developmental or educational difficulties as 'Presence or absence of learning, developmental or educational difficulties'

- [x] rename 'Emotional or behavioural problems' as 'Presence or absence of emotional or behavioural problems'

- [x] there should also be a field in this list title "The approximate frequency or number of episodes since the first episode" with the answers yes / no.

- [x] "Is epilepsy suspected?" is a redundant question and field as is true by definition of entry criteria

**Comment by pacharanero** [comment] 2022-10-17 14:08
>"Is epilepsy suspected?" is a redundant question and field as is true by definition of entry criteria
This is a duplicate of #112 so I will mark it as completed here and track progress in the Issue

**Comment by pacharanero** [comment] 2022-10-17 14:08
The other bullet points in this issue need addressing with @eatyourpeas and myself working together to implement

**Comment by eatyourpeas** [comment] 2022-10-17 14:17
@pacharanero these are already refactored in #108 branch

**Closed as completed** 2022-10-17 16:05 UTC
