### ISSUE TITLE
timer for user to complete a record

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#938] opened 2024-05-02 12:03 UTC
At the webinar a user requested a timer to report time spent filling in each record. They would use this to apply for funding in their trust to cover time spent contributing to E12

**Comment by mbarton** [comment] 2024-05-02 12:37
Closing as a dupe of https://github.com/rcpch/rcpch-audit-engine/issues/939 :)

**Closed as completed by mbarton** 2024-05-02 12:37 UTC
Labels: feature request
