### ISSUE TITLE
Question icon to contact RCPCH to add items to dropdowns

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#451] opened 2023-04-28 16:59 UTC

**Comment by anchit-chandran** [comment] 2023-05-02 14:40
?duplicate of #163

**Comment by pacharanero** [comment] 2023-08-31 14:11
This is going to be handled by email to the E12 team who can pass on relevant ones to the dev team

**Closed as completed by pacharanero** 2023-08-31 14:11 UTC
Labels: duplicate, feature request
